# @package _group_
common:
  bf16: true
  log_format: json
  log_interval: 200
  use_plasma_view: false
  tensorboard_logdir: tb
  verbose_grad_logging: .*(?:\.layers\.[0-9]+|\.embed_tokens|\.embed_positions|\.output_projection|\.lm_head|rtd_head)\.

checkpoint:
  no_epoch_checkpoints: true
  save_interval_updates: 125000

task:
  _name: t5_metro
  data: ???
  sample_break_mode: complete_doc
  tokens_per_sample: 512
  shorten_method: random_crop
  shorten_data_split_list: train

criterion:
  _name: t5_metro
  discriminator_loss_weight: 1.0
  masked_positions_only: lm
  rtd_loss_weight: 50.0

dataset:
  max_tokens: 2048
  required_batch_size_multiple: 2
  ignore_unused_valid_subsets: true
  skip_invalid_size_inputs_valid_test: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 2.0
  lr: [0.0001]
  max_update: 2000000
  update_freq: [2]  # Assuming 256 GPUs
  skip_remainder_batch: true

model:
  _name: t5_metro_large_rpe
  generator_zero_dropout: true
  generator_layers: 6
  rtd_head: roberta
  share_generator_discriminator_embed: true
  max_positions: 1024
